
## MySQL connect
spring:
  datasource:
    url : jdbc:mysql://localhost:3306/layer?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username : root
    password : 1234
    driver-class-name=com: com.mysql.cj.jdbc.Driver

## JPA setting
  jpa:
    hibernate:
      ddl-auto : create
    properties :
      hibernate :
        format_sql : true
        show-sql : true

## MySQL dialect
    database-platform : org.hibernate.dialect.MySQLDialect

## log
logging:
  level:
    org.hibernate.SQL : debug
    org.hibernate.orm.jdbc.bind: trace